throw error if amending empty commit (#1322)
**Context:**

amending an empty branch will cause our metadata to mess up since we'd be changing the commit.

**Changes In This Pull Request:**

throw an error if we're trying to amend an empty commit

**Test Plan:**
```
ngobrendan@ip-192-168-86-164 graphite-cli[main] gt bc -m "empty branch"
No staged changes; created a branch with no commit.
ngobrendan@ip-192-168-86-164 graphite-cli[11-15-empty_branch] gt ls
◯        11-15-update_messaging_for_continues_that_use_git_rebase_directly
│ ◯      11-15-fix_don_t_require_stages_commits_on_amends
│ │ ◯    11-15-throw_error_if_amending_empty_commit
│ │ │ ◉  11-15-empty_branch
◯─┴─┴─┘  main
ngobrendan@ip-192-168-86-164 graphite-cli[11-15-empty_branch] yarn cli ca -an  
ERROR: No commits in this branch to amend
```